//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EducationPlatform.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Certificate
    {
        public int Id { get; set; }
        public string RecomendBy { get; set; }
        public Nullable<int> RecommderId { get; set; }
        public Nullable<int> ApplierId { get; set; }
        public Nullable<int> CourseId { get; set; }
        public string Status { get; set; }
        [Required(ErrorMessage = "Please provide Comments")]
        public string Comments { get; set; }
        [Required(ErrorMessage = "Please provide Date")]
        public Nullable<System.DateTime> Date { get; set; }
    }
}
