//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EducationPlatform.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Counseling
    {
        public int Id { get; set; }
        public Nullable<int> MentorId { get; set; }
        public Nullable<int> StudentId { get; set; }
        public Nullable<int> CourseId { get; set; }
        [Required(ErrorMessage = "Please provide Link")]
        public string MeetLink { get; set; }
        [Required(ErrorMessage = "Please provide Details")]
        public string Details { get; set; }
        [Required(ErrorMessage = "Please provide Date")]
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Mentor Mentor { get; set; }
        public virtual Student Student { get; set; }
    }
}
