//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EducationPlatform.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Cours
    {
        public Cours()
        {
            this.Carts = new HashSet<Cart>();
            this.CourseDetails = new HashSet<CourseDetail>();
            this.Notices = new HashSet<Notice>();
            this.Ratings = new HashSet<Rating>();
            this.Transactions = new HashSet<Transaction>();
        }
    
        public int Id { get; set; }

        [Required(ErrorMessage = "Please provide Name")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Please provide Details")]
        public string Details { get; set; }
        [Required(ErrorMessage = "Please provide Price")]
        public Nullable<double> Price { get; set; }
        [Required(ErrorMessage = "Please provide Duration")]
        public string Duration { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        [Required(ErrorMessage = "Please provide Photo URL")]
        public string Photo { get; set; }
        [Required(ErrorMessage = "Please provide Institution Id")]
        public Nullable<int> InstitutionId { get; set; }
        [Required(ErrorMessage = "Please provide Mentor Id")]
        public Nullable<int> MentorId { get; set; }
    
        public virtual ICollection<Cart> Carts { get; set; }
        public virtual ICollection<CourseDetail> CourseDetails { get; set; }
        public virtual ICollection<Notice> Notices { get; set; }
        public virtual ICollection<Rating> Ratings { get; set; }
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}
