//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EducationPlatform.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Mentor
    {
        public Mentor()
        {
            this.Counselings = new HashSet<Counseling>();
            this.CourseDetails = new HashSet<CourseDetail>();
        }
    
        public int Id { get; set; }
       [Required(ErrorMessage = "Please provide Name")]
    
        public string Name { get; set; }
       [Required(ErrorMessage = "Please provide address")]
        public string Address { get; set; }
        [Required(ErrorMessage = "Please provide Email")]
        [EmailAddress(ErrorMessage = "Email format not matched ")]
        public string Email { get; set; }
       [Required(ErrorMessage = "Please provide Phone Number")]
        [Phone(ErrorMessage = "Please provide Phone number")]
        public string Phone { get; set; }
        [Required(ErrorMessage = "Please provide Password")]
        public string Password { get; set; }
        public byte[] Photo { get; set; }

        public string Gender { get; set; }
        [Required(ErrorMessage = "Please provide Institution")]
        public string Institution { get; set; }
        public string IsValid { get; set; }
    
        public virtual ICollection<Counseling> Counselings { get; set; }
        public virtual ICollection<CourseDetail> CourseDetails { get; set; }
    }
}
